[build]
  command = "npm run build"
  publish = "public"

[context.branch-deploy]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = ""
    Cache-Control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''
